<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_scope_privilege">
    <sys_scope_privilege action="INSERT_OR_UPDATE">
        <operation>read</operation>
        <source_scope display_value="PythonConnector">e9c840822f712010f101ad2ef699b602</source_scope>
        <status>allowed</status>
        <sys_class_name>sys_scope_privilege</sys_class_name>
        <sys_created_by>admin</sys_created_by>
        <sys_created_on>2021-01-20 16:36:30</sys_created_on>
        <sys_id>5ff1f5062fb12010f101ad2ef699b686</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>incident</sys_name>
        <sys_package display_value="PythonConnector" source="x_125590_pythoncon">e9c840822f712010f101ad2ef699b602</sys_package>
        <sys_policy/>
        <sys_scope display_value="PythonConnector">e9c840822f712010f101ad2ef699b602</sys_scope>
        <sys_update_name>sys_scope_privilege_5ff1f5062fb12010f101ad2ef699b686</sys_update_name>
        <sys_updated_by>admin</sys_updated_by>
        <sys_updated_on>2021-01-20 16:36:30</sys_updated_on>
        <target_name>incident</target_name>
        <target_scope display_value="Global">global</target_scope>
        <target_type>sys_db_object</target_type>
    </sys_scope_privilege>
</record_update>
